[manifest]
version = "1.0.0"
dump_lua = true
priority = 100000000

# ==========================================================================
# Big thank you to hastagguigui and OneSuchKeeper for the following patches!
# ==========================================================================

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "if _front and _front.suit and (_front.value == 'Jack' or _front.value == 'Queen' or _front.value == 'King') then"
position = "at"
payload = '''
local rank_suffix = _front.value
local _collabb = G.SETTINGS.CUSTOM_DECK.Collabs[_front.suit]
if _front and _front.suit and _collabb then
	local position_x = -1
	for k, v in ipairs(G.COLLABS.options[_front.suit][_collabb]) do
		if v == rank_suffix then position_x = k-1 end
	end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = "return G.ASSET_ATLAS[_collab..'_'..(G.SETTINGS.colourblind_option and 2 or 1)], G.COLLABS.pos[_front.value]"
position = "at"
payload = '''

local offset_y = 0
if G.COLLABS.options[_front.suit][_collab].ALL_SUITS then
    if _front.suit == "Hearts" then
        offset_y = 0
    end

    if _front.suit == "Clubs" then
        offset_y = 1
    end

    if _front.suit == "Diamonds" then
        offset_y = 2
    end

    if _front.suit == "Spades" then
        offset_y = 3
    end
end

if position_x > -1 then
	return G.ASSET_ATLAS[_collab..'_'..(G.SETTINGS.colourblind_option and 2 or 1)], {x=position_x, y=offset_y}
end'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''for k, v in pairs(G.COLLABS.options[_suit]) do'''
position = "at"
payload = '''
for _, skin in ipairs(G.EXTRA_SKINS_NAMES[_suit]) do
	loc_options[#loc_options+1] = skin
end
sendDebugMessage(tprint(G.EXTRA_SKINS_NAMES))
for k, v in pairs(G.COLLABS.list[_suit]) do'''
match_indent = true


[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "local faces = {'K','Q','J'}"
position = "at"
payload = "local faces = {'A','K','Q','J','T','9','8','7','6','5','4','3','2'}"
match_indent = true

[[patches]]
[patches.regex]
target = "functions/UI_definitions.lua"
pattern = '''(?<indent>[\t ]*)4\*G\.CARD_W,'''
position = "at"
payload = '''8*G.CARD_W,'''

[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = "self.METRICS = {"
position = "before"
payload = '''self.COLLABS = {
list = {
    Spades = {"default", "collab_TW", "collab_CYP"},
    Hearts = {"default", "collab_AU", "collab_TBoI"},
    Clubs = {"default", "collab_VS", "collab_STS"},
    Diamonds = {"default", "collab_DTD", "collab_SV"},
},
options = {
    Spades = {
        default = {},
        collab_TW = {"Jack", "Queen", "King"},
        collab_CYP = {"Jack", "Queen", "King"}
    },
    Hearts = {
        default = {},
        collab_AU = {"Jack", "Queen", "King"},
        collab_TBoI = {"Jack", "Queen", "King"}
    },
    Clubs = {
        default = {},
        collab_VS = {"Jack", "Queen", "King"},
        collab_STS = {"Jack", "Queen", "King"}
    },
    Diamonds = {
        default = {},
        collab_DTD = {"Jack", "Queen", "King"},
        collab_SV = {"Jack", "Queen", "King"}
    }
},
}'''

match_indent = true
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "for i = 1, 3 do"
position = "at"
payload = "for i = 1, #faces do"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "G.SETTINGS.CUSTOM_DECK.Collabs[args.cycle_config.curr_suit] = G.COLLABS.options[args.cycle_config.curr_suit][args.to_key] or 'default'"
position = "at"
payload = '''
G.SETTINGS.CUSTOM_DECK.Collabs[args.cycle_config.curr_suit] = G.COLLABS.list[args.cycle_config.curr_suit][args.to_key] or 'default'
'''
match_indent = true
